### ISSUE TITLE
Exception: Dependency not found: ffmpeg

### ISSUE THREAD

**Issue by Yuelioi** [BingLingGroup/autosub#111]
之前使用的py2.7的隔壁的autosub没问题 
使用alpha版本没问题  然后看到issue可以pip直装py3  
试了下 反馈ffmpeg配置有问题如下
然后我不管重新添加了FFMPEG_PATH还是之前添加的path里加了C:\ffmpeg\bin(我的安装目录)

-----------------------------------------------------------------------------------------
使用命令:autosub C:\Users\yl\Desktop\1.mp4 -S en -D en

```
Traceback (most recent call last):</br>
File "C:\Python37\Scripts\autosub-script.py", line 11, in <module>
    load_entry_point('autosub==0.4.0', 'console_scripts', 'autosub')()
  File "c:\python37\lib\site-packages\autosub\__init__.py", line 404, in main
    output=args.output,
  File "c:\python37\lib\site-packages\autosub\__init__.py", line 245, in generate_subtitles
    audio_filename, audio_rate = extract_audio(source_path)
  File "c:\python37\lib\site-packages\autosub\__init__.py", line 185, in extract_audio
    raise Exception("Dependency not found: ffmpeg")
Exception: Dependency not found: ffmpeg
```

-----------------------------------------------------------------------------------------
- 操作系统:windows
- Python版本: Python 3.7
- Autosub版本: pip install git+https://github.com/agermanidis/autosub.git@master

**Comment by Yuelioi** [comment]
https://github.com/agermanidis/autosub/issues/94

**Comment by BingLingGroup** [comment]
老版本的路径查找确实有点奇怪，一直到最新的0.5.6a才改得差不多……下个版本可能会加入一个允许在命令行输入路径的功能。
