### ISSUE TITLE
I can't open autosub

### ISSUE THREAD

**Issue by gabriellluz** [BingLingGroup/autosub#142]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
I can't even use autosub. When I type autosub, I get an error.

**To Reproduce**
Open a terminal windows
Type autosub

- Command line arguments you are using.Use the following markdown code block syntax is recommended. Copy them into the place between \`\`\`.

```
autosub
```

- A complete copy of command line output of the autosub. You can use `Ctrl-A` and `Ctrl-C` to copy all of them. 

```
Traceback (most recent call last):
  File "/home/mestre/.pyenv/versions/3.8.5/bin/autosub", line 11, in <module>
    load_entry_point('autosub==0.5.7a0', 'console_scripts', 'autosub')()
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/autosub/__init__.py", line 16, in <module>
    from autosub import ffmpeg_utils
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/autosub/ffmpeg_utils.py", line 18, in <module>
    from autosub import constants
  File "/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/autosub/constants.py", line 16, in <module>
    from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' (/home/mestre/.pyenv/versions/3.8.5/lib/python3.8/site-packages/google/cloud/speech_v1p1beta1/__init__.py)
```

- If a config file is used, attach the config file, but be sure to remove any information related to your accounts.

```json
Use this to display your config.
```

- etc.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. But it is not recommended using screenshots to demonstrate the commandline output unless you think it really matters.

**Environment (please complete the following information):**

- OS: Ubuntu Focal 20.04, x64
- Python Version: Python 3.8.5
- Autosub Version: autosub==0.5.7a0

**Additional context** (Optional)

**Comment by BingLingGroup** [comment]
It seems that google has changed its package. I will investigate this issue later.

**Comment by BingLingGroup** [comment]
This commit https://github.com/BingLingGroup/autosub/pull/144/commits/3489be835e1d6e7a01e45308190111961c8c6fcb temporarily limits the version of the google-cloud-speech package below 2.0.0. Maybe support it in the future.
