### ISSUE TITLE
语音转文字中途报错

### ISSUE THREAD

**Issue by simalaozeiyu** [BingLingGroup/autosub#152]
使用autosub 0.5.7a版本进行语音转文字的中途 每次都会报错如下

> `语音转文字中：  45% |########################################                                                 | ETA:   0语音转文字中：  45% |########################################                                                 | ETA:   0:05:24multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "site-packages\urllib3\response.py", line 601, in _update_chunk_length
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\response.py", line 360, in _error_catcher
  File "site-packages\urllib3\response.py", line 666, in read_chunked
  File "site-packages\urllib3\response.py", line 605, in _update_chunk_length
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\models.py", line 750, in generate
  File "site-packages\urllib3\response.py", line 490, in stream
  File "site-packages\urllib3\response.py", line 694, in read_chunked
  File "contextlib.py", line 130, in __exit__
  File "site-packages\urllib3\response.py", line 378, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\pool.py", line 121, in worker
  File "autosub\api_google.py", line 211, in __call__
  File "site-packages\requests\api.py", line 116, in post
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 686, in send
  File "site-packages\requests\models.py", line 828, in content
  File "site-packages\requests\models.py", line 753, in generate
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "autosub\__main__.py", line 25, in <module>
  File "autosub\__init__.py", line 159, in main
  File "autosub\cmdline_utils.py", line 1215, in audio_or_video_prcs
  File "autosub\core.py", line 155, in gsv2_to_text
  File "multiprocessing\pool.py", line 748, in next
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
[5852] Failed to execute script __main__`

- 操作系统: windows 10 专业版 64位
- Python版本: Python 3.6
- Autosub版本: 0.57a

**Comment by BingLingGroup** [comment]
请按照issue格式填写
