### ISSUE TITLE
speech_v1p1beta1导入enums失败

### ISSUE THREAD

**Issue by qiqiApink** [BingLingGroup/autosub#154]
```
$ autosub
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/autosub/bin/autosub", line 5, in <module>
    from autosub import main
  File "/home/xxx/anaconda3/envs/autosub/lib/python3.6/site-packages/autosub/__init__.py", line 16, in <module>
    from autosub import ffmpeg_utils
  File "/home/xxx/anaconda3/envs/autosub/lib/python3.6/site-packages/autosub/ffmpeg_utils.py", line 18, in <module>
    from autosub import constants
  File "/home/xxx/anaconda3/envs/autosub/lib/python3.6/site-packages/autosub/constants.py", line 16, in <module>
    from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums'
```

**Comment by BingLingGroup** [comment]
Duplicated #142
