### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Andrea-lyz** [BingLingGroup/autosub#156]
#155 安装googletrans 4.0.0rc1后，出现以下错误

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/autosub", line 8, in <module>
sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/__init__.py", line 170, in main
    cmdline_utils.sub_trans(args,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/cmdline_utils.py", line 796, in sub_trans
    translated_text, args.src_language = core.list_to_googletrans(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/core.py", line 578, in list_to_googletrans
    translator = googletrans.Translator(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/googletrans/client.py", line 88, in __init__
    client=self.client, host=self.service_urls[0])
TypeError: 'NoneType' object is not subscriptable`
   麻烦大大@BingLingGroup 教我如何解决，国外上课急需555

**Comment by BingLingGroup** [comment]
可以按照issue格式填写吗

**Comment by BingLingGroup** [comment]
刚才试了下 #155 中的解决方法，使用autosub dev分支最新代码，成功安装后没遇到你说的这个问题

**Comment by Ed20010424** [comment]
> 刚才试了下 #155 中的解决方法，使用autosub dev分支最新代码，成功安装后没遇到你说的这个问题

抱歉没有按照格式提交issue，算是第一次在github提交issue，对不起

操作系统：[Mac OS Big Sur 11.0.1]
Python版本：[Python 3.8.6 for Mac]
安装代码
```
usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install ffmpeg git
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
Sudo python3 get-pip.py
pip3 install git+https://github.com/BingLingGroup/autosub.git@alpha ffmpeg-normalize langcodes
```
- 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。

```
/Users/zhengdan/Desktop/test/cn.command ; exit;                                 
zhengdan@zhengdandeMacBook-Air ~ % /Users/zhengdan/Desktop/test/cn.command ; exit;
没有指定输出格式。使用输入的格式"srt"作为输出格式。
输入是一个字幕文件。
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/autosub", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/__init__.py", line 170, in main
    cmdline_utils.sub_trans(args,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/cmdline_utils.py", line 796, in sub_trans
    translated_text, args.src_language = core.list_to_googletrans(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/autosub/core.py", line 578, in list_to_googletrans
    translator = googletrans.Translator(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/googletrans/client.py", line 88, in __init__
    client=self.client, host=self.service_urls[0])
TypeError: 'NoneType' object is not subscriptable
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

请问是因为Mac os的缘故吗，还是因为我是从alpha版本安装的原因？
我晚些时候尝试从windows环境安装，Mac是我朋友的，他也想使用autosub，希望能解决此问题
感谢您的回复
