### ISSUE TITLE
我停留在autosub.exe 那里

### ISSUE THREAD

**Issue by joshuayee86** [BingLingGroup/autosub#161]
autosub install了可是就是autosub不成功

key 了 autosub.exe出现这样的字母

 Traceback (most recent call last):
  File "c:\users\joshua\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\joshua\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\joshua\anaconda3\Scripts\autosub.exe\__main__.py", line 4, in <module>
  File "c:\users\joshua\anaconda3\lib\site-packages\autosub\__init__.py", line 16, in <module>
    from autosub import ffmpeg_utils
  File "c:\users\joshua\anaconda3\lib\site-packages\autosub\ffmpeg_utils.py", line 18, in <module>
    from autosub import constants
  File "c:\users\joshua\anaconda3\lib\site-packages\autosub\constants.py", line 16, in <module>
    from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' (c:\users\joshua\anaconda3\lib\site-packages\google\cloud\speech_v1p1beta1\__init__.py)

**Comment by BingLingGroup** [comment]
Duplicated #142
