### ISSUE TITLE
alpha pyinstaller 0.5.7 版本的autosub 在翻译字幕时报错

### ISSUE THREAD

**Issue by 1br8s4gs4** [BingLingGroup/autosub#165]
输出内容如下：
D:\autosub-0.5.7-alpha-win-x64-pyinstaller\autosub_pyinstaller>.\autosub -i ".\0
1.ja_jp.srt"  -D zh-cn -F ass -surl translate.google.cn
输入是一个字幕文件。
Traceback (most recent call last):
  File "autosub\__main__.py", line 25, in <module>
  File "autosub\__init__.py", line 173, in main
  File "autosub\cmdline_utils.py", line 804, in sub_trans
  File "autosub\core.py", line 635, in list_to_googletrans
  File "site-packages\googletrans\client.py", line 249, in detect
  File "site-packages\googletrans\client.py", line 75, in _translate
  File "site-packages\googletrans\gtoken.py", line 200, in do
  File "site-packages\googletrans\gtoken.py", line 65, in _update
AttributeError: 'NoneType' object has no attribute 'group'
[4728] Failed to execute script __main__

**Comment by BingLingGroup** [comment]
Duplicated #155
