### ISSUE TITLE
MacOS下pip安装alpha版本无法使用

### ISSUE THREAD

**Issue by AshramC** [BingLingGroup/autosub#181]
我的系统版本是macOS 11.4，python版本是3.8，按照步骤安装了alpha版本，在终端中输入autosub -h后报错

Traceback (most recent call last):
  File "/Users/ashramc/opt/anaconda3/bin/autosub", line 5, in <module>
    from autosub import main
  File "/Users/ashramc/opt/anaconda3/lib/python3.8/site-packages/autosub/__init__.py", line 16, in <module>
    from autosub import ffmpeg_utils
  File "/Users/ashramc/opt/anaconda3/lib/python3.8/site-packages/autosub/ffmpeg_utils.py", line 18, in <module>
    from autosub import constants
  File "/Users/ashramc/opt/anaconda3/lib/python3.8/site-packages/autosub/constants.py", line 16, in <module>
    from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' (/Users/ashramc/opt/anaconda3/lib/python3.8/site-packages/google/cloud/speech_v1p1beta1/__init__.py)

是不是版本有什么问题，谢谢

**Comment by BingLingGroup** [comment]
用pip安装最新dev版即可解决问题

**Comment by BingLingGroup** [comment]
Duplicated #142
