### ISSUE TITLE
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1'

### ISSUE THREAD

**Issue by msyzzm** [BingLingGroup/autosub#184]
**Describe the bug**
autosub can not run

**To Reproduce**
Install alpha branch, then run autosub.

```
autosub
```
```
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 5, in <module>
    from autosub import main
  File "/usr/local/lib/python3.8/dist-packages/autosub/__init__.py", line 16, in <module>
    from autosub import ffmpeg_utils
  File "/usr/local/lib/python3.8/dist-packages/autosub/ffmpeg_utils.py", line 18, in <module>
    from autosub import constants
  File "/usr/local/lib/python3.8/dist-packages/autosub/constants.py", line 16, in <module>
    from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' (/usr/local/lib/python3.8/dist-packages/google/cloud/speech_v1p1beta1/__init__.py)
```

**Environment (please complete the following information):**

- OS: ubuntu 20.04
- Python Version: Python 3.8
- Autosub Version: 0.5.7a

**Comment by BingLingGroup** [comment]
Duplicated #142
