### ISSUE TITLE
httplib.ResponseNotReady issue

### ISSUE THREAD

**Issue by bertonlee** [BingLingGroup/autosub#59]
```
Converting speech regions to FLAC files: 100% |########################################################| Time:  0:00:19
Performing speech recognition: 100% |##################################################################| Time:  0:02:28
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\autosub.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 416, in main
    output=args.output,
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 291, in generate_subtitles
    src=src_language)
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 128, in __init__
    developerKey=self.api_key)
  File "c:\python27\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 223, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 273, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 2135, in request
    cachekey,
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1796, in _request
    conn, request_uri, method, body, headers
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1737, in _conn_request
    response = conn.getresponse()
  File "c:\python27\lib\httplib.py", line 1108, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady
```
使用的是window，音频(英语)转英文没问题，转中文，就是要翻译就存在这个问题。是我什么地方没配置好吗？

**Comment by BingLingGroup** [comment]
问题解决了吗？我感觉就是单纯的网络不好吧，我翻译没遇到这个问题，使用的最新版0.5.1a，看错误应该是网络连接不稳定吧。
两种[解决方法](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#代理支持)。如果是稳定的梯子的话，可以考虑自己购买使用readme的telegram频道里推荐的梯子。（无保证，需要自己测试）

**Comment by bertonlee** [comment]
> 问题解决了吗？我感觉就是单纯的网络不好吧，我翻译没遇到这个问题，使用的最新版0.5.1a，看错误应该是网络连接不稳定吧。
> 两种[解决方法](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E4%BB%A3%E7%90%86%E6%94%AF%E6%8C%81)。如果是稳定的梯子的话，可以考虑自己购买使用自述的电报频道里推荐的梯子。（无保证，需要自己测试）

嗯嗯，解决了，看了其他的issues，有讲解，主要原因是window终端命令需要配置http_proxy来支持google翻译的api访问

**Comment by BingLingGroup** [comment]
输入`-hsp`也可以的，效果和提前输入`set https_proxy=https://127.0.0.1:1080`一样。
那我关了。

**Comment by bertonlee** [comment]
> 输入`-hsp`也可以的，效果和提前输入`set https_proxy=https://127.0.0.1:1080`一样。
> 那我关了。

嗯嗯，好的，有了解，非常感谢。

**Comment by D170302066** [comment]
-hsp命令是在哪里输入呢？

在2019-08-22 22:37:23，d170302066@st.shou.edu.cn写道：

输入-hsp也可以的，效果和提前输入set https_proxy=https://127.0.0.1:1080一样。
那我关了。

嗯嗯，好的，有了解，非常感谢。

**Comment by BingLingGroup** [comment]
@D170302066 加在你原先的参数后面就可以了
