### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by msongz** [BingLingGroup/autosub#69]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
无法将英文字幕翻译为中文字幕

**复现问题**
复现问题的步骤:
1. 你使用的命令行参数。
2. 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。推荐使用以下的代码块markdown语法。

```
autosub -i /Users/tobobo/Downloads/2-2.srt -SRC en -D zh-cn
没有指定输出格式。使用输入的格式"srt"作为输出格式。
输入是一个字幕文件。

从"en"翻译为"zh-cn"。
翻译中： N/A% |                                                                                      | ETA:  --:-翻译中：   0% |                                                                                      | ETA:   0:1翻译中：  11% |##########                                                                            | ETA:   0:0翻译中：  21% |##################                                                                    | ETA:   0:00:48Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 11, in <module>
    load_entry_point('autosub==0.5.2a0', 'console_scripts', 'autosub')()
  File "/Library/Python/2.7/site-packages/autosub/__init__.py", line 150, in main
    styles_list=None)
  File "/Library/Python/2.7/site-packages/autosub/cmdline_utils.py", line 631, in subs_trans
    service_urls=args.service_urls
  File "/Library/Python/2.7/site-packages/autosub/core.py", line 325, in list_to_googletrans
    src=src_language)
  File "/Library/Python/2.7/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/Library/Python/2.7/site-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "/Library/Python/2.7/site-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "/Library/Python/2.7/site-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

3. 等等

**期待的行为**
清晰并准确地描述你本想做的事情。

**截图**
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

**操作环境（请提供以下完整数据）：**
 - 操作系统: [譬如 windows] macOS 10.13
 - Python版本: [譬如 Python 2.7] 2.7
 - Autosub版本: [譬如 0.4.0] 最新的 dev 分支

**额外信息**（可选）
任何其他的能描述问题的信息。

**Comment by BingLingGroup** [comment]
看起来是你没有使用代理导致googletrans没有接收到东西，如果不使用`-hsp`通过https代理连接谷歌翻译网页的话，建议使用`--service-urls`将谷歌翻译网页定义为国内可用的url，如`translate.google.cn`
