### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序

### ISSUE THREAD

**Issue by jsuispersonne** [BingLingGroup/autosub#78]
（抱歉此前格式不正确）更新Windows之后再使用时出现OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**复现问题**
使用方式和更新前完全相同，
C:\Users\hp\Downloads\autosub\autosub\autosub>autosub -i "C:\Users\hp\Music\004.m4a" -S "fr-FR" -F "txt" -der
音频返回本地时出现问题，提示与32位不兼容。电脑是64位。
ffprobe C:\Users\hp\AppData\Local\Temp\tmp9o7d3x5u.flac -show_format -pretty -loglevel quiet
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\__main__.py", line 26, in <module>
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\autosub\__init__.py", line 138, in main
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\autosub\cmdline_utils.py", line 913, in audio_or_video_prcs
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\autosub\core.py", line 91, in bulk_audio_conversion
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\context.py", line 118, in Pool
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\pool.py", line 174, in __init__
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\pool.py", line 239, in _repopulate_pool
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\process.py", line 105, in start
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\context.py", line 313, in _Popen
  File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\popen_spawn_win32.py", line 49, in __init__
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**操作环境（请提供以下完整数据）：**
 - 操作系统: windows 10
 - Python版本: python2 v2.7.17
 - Autosub版本: autosub 0.5.3-alpha by Anastasis Germanidis (于本页下载)

![屏幕截图(1)](https://user-images.githubusercontent.com/59540895/73405322-dff3bb80-42f3-11ea-818b-8ade3f430e57.png)

**Comment by jsuispersonne** [comment]
python版本是64位

**Comment by BingLingGroup** [comment]
你换成python 3.7试试。
今年python2.7已经不维护了，以后autosub也会放弃对python2.7的支持。
当然我这里的python2.7.15是可以用的，我不清楚是不是python2.7.17的问题。

**Comment by BingLingGroup** [comment]
另外你可以谷歌一下这个问题的解决方案 [OSError: [WinError 193] %1 - Google 搜索](https://www.google.com/search?q=OSError%3A%20[WinError%20193]%20%251)

**Comment by jsuispersonne** [comment]
> 另外你可以谷歌一下这个问题的解决方案 [OSError: [WinError 193] %1 - Google 搜索](https://www.google.com/search?q=OSError%3A%20%5BWinError%20193%5D%20%251)

用chocolatey更新python到了python3.8.1 依然出现同样问题
` File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\popen_spawn_win32.py", line 49, in __init__
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。`

google后用anaconda切换到32位环境和32位python3.6还是同样问题。。。
`C:\WINDOWS\system32>conda create -n python32 python=3.6
C:\WINDOWS\system32>conda activate python32 (python32) C:\WINDOWS\system32>cd C:\Users\hp\Downloads\autosub\autosub\autosub

(python32) C:\Users\hp\Downloads\autosub\autosub\autosub>autosub -i C:\Users\hp\Music\004.m4a -S fr-FR -F txt -der
File "C:\Users\hp\Downloads\autosub\autosub\autosub\multiprocessing\popen_spawn_win32.py", line 49, in __init__
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。`

**Comment by BingLingGroup** [comment]
我看到的一个解决方法是先搞清楚你的PATH变量，看有没有冲突的地方。
另外你试过我打包的release版本没有，那个是不需要依赖，可以独立运行的。

**Comment by jsuispersonne** [comment]
> 我看到的一个解决方法是先搞清楚你的PATH变量，看有没有冲突的地方。
> 另外你试过我打包的release版本没有，那个是不需要依赖，可以独立运行的。

之前我就是下载的您的版本。我删掉了之前的path，重新下载了您的版本，现在运行成功了。谢谢！
