### ISSUE TITLE
Running Error: AttributeError: 'Namespace' object has no attribute 'lines_per_trans'

### ISSUE THREAD

**Issue by ColliderConquer** [BingLingGroup/autosub#80]
The operating system is Windows 10.
I've downloaded the autosub-0.5.4-alpha-win-x64-pyinstaller.7z and installed all the required library of python.
Run with the command ".\autosub -S en-US -i "1.mp4"" and got the error as below,

Traceback (most recent call last):
  File "autosub\__main__.py", line 26, in <module>
  File "autosub\__init__.py", line 142, in main
  File "autosub\cmdline_utils.py", line 255, in validate_aovp_args
AttributeError: 'Namespace' object has no attribute 'lines_per_trans'
[207576] Failed to execute script __main__

What should I do the following? thank you.

**Comment by BingLingGroup** [comment]
I replace the release. The [new release](https://github.com/BingLingGroup/autosub/releases/tag/0.5.4-alpha) should fix this.

**Comment by BingLingGroup** [comment]
这是[这个视频](https://www.bilibili.com/video/av55733388?p=8)识别好的英文字幕
[97434509-1-192.en-US.zip](https://github.com/BingLingGroup/autosub/files/4144204/97434509-1-192.en-US.zip)
