### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Yuelioi** [BingLingGroup/autosub#95]
我的代码是 autosub -i C:\Python37\77.mp4 -S en-us

结果Traceback (most recent call last):
  File "C:\Python37\Scripts\autosub-script.py", line 11, in <module>
    load_entry_point('autosub==0.5.4a0', 'console_scripts', 'autosub')()
  File "C:\Python37\lib\site-packages\autosub-0.5.4a0-py3.7.egg\autosub\__init__.py", line 147, in main
    styles_list=styles_list)
  File "C:\Python37\lib\site-packages\autosub-0.5.4a0-py3.7.egg\autosub\cmdline_utils.py", line 876, in audio_or_video_prcs
    if not ffmpeg_utils.ffprobe_check_file(audio_wav):
  File "C:\Python37\lib\site-packages\autosub-0.5.4a0-py3.7.egg\autosub\ffmpeg_utils.py", line 150, in ffprobe_check_file
    shell=False)
  File "C:\Python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by BingLingGroup** [comment]
你安装了ffprobe没？ 0.5.4a在依赖查找方面还有些问题，建议安装dev分支最新版。

```
pip install git+https://github.com/BingLingGroup/autosub.git@dev --upgrade
```

**Comment by BingLingGroup** [comment]
太长时间没有回复，先关了，关闭以后仍可以回复。

**Comment by Yuelioi** [comment]
使用的是:pip install git+https://github.com/BingLingGroup/autosub.git@dev --upgrade

```
C:\Users\yl>autosub -i "C:\Users\yl\Desktop\1.mp4" -S en-us
翻译目的语言未提供。只进行语音识别。
语音语言和目的语言一致。只进行语音识别。

将源文件转换为"C:\Users\yl\AppData\Local\Temp\tmpp0hlctdf.wav"来检测语音区域。
C:\ffmpeg\bin\ffmpeg.exe -hide_banner -y -i "C:\Users\yl\Desktop\1.mp4" -vn -ac 1 -ar 48000 -loglevel error "C:\Users\yl\AppData\Local\Temp\tmpp0hlctdf.wav"

使用ffprobe来检查转换结果。
C:\ffmpeg\bin\ffprobe.exe "C:\Users\yl\AppData\Local\Temp\tmpp0hlctdf.wav" -show_format -pretty -loglevel quiet
[FORMAT]
filename=C:\Users\yl\AppData\Local\Temp\tmpp0hlctdf.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=0:03:27.516750
size=18.998800 Mibyte
bit_rate=768.003000 Kbit/s
probe_score=99
TAG:encoder=Lavf58.42.100
[/FORMAT]

转换完毕。
使用Auditok检测语音区域。
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\auditok-0.2.0a0-py3.7.egg\auditok\util.py", line 1007, in __getattr__
    return getattr(self._audio_source, name)
  File "c:\python37\lib\site-packages\auditok-0.2.0a0-py3.7.egg\auditok\util.py", line 856, in __getattr__
    return getattr(self._audio_source, name)
  File "c:\python37\lib\site-packages\auditok-0.2.0a0-py3.7.egg\auditok\util.py", line 736, in __getattr__
    return getattr(self._audio_source, name)
AttributeError: 'BufferAudioSource' object has no attribute 'get_sample_width'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\autosub-script.py", line 11, in <module>
    load_entry_point('autosub==0.5.6a0', 'console_scripts', 'autosub')()
  File "c:\python37\lib\site-packages\autosub\__init__.py", line 159, in main
    styles_list=styles_list)
  File "c:\python37\lib\site-packages\autosub\cmdline_utils.py", line 1116, in audio_or_video_prcs
    mode=mode)
  File "c:\python37\lib\site-packages\autosub\core.py", line 51, in auditok_gen_speech_regions
    sample_width=asource.get_sample_width(),
  File "c:\python37\lib\site-packages\auditok-0.2.0a0-py3.7.egg\auditok\util.py", line 1010, in __getattr__
    "'AudioReader' has no attribute '{}'".format(name)
AttributeError: 'AudioReader' has no attribute 'get_sample_width'
```
